# Generated by Django 3.1.5 on 2022-05-02 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 5, 2, 8, 19, 19, 713213, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
