# Generated by Django 3.1.5 on 2022-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.CharField(default='', max_length=20),
        ),
    ]
