# Generated by Django 3.1.5 on 2022-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='message',
            field=models.CharField(max_length=300000),
        ),
    ]
