# Generated by Django 3.1.5 on 2022-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220502_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
